ARG FRAPPE_IMAGE=frappe/erpnext
ARG FRAPPE_TAG=v16.10.1
FROM ${FRAPPE_IMAGE}:${FRAPPE_TAG}

# Copy the custom app source into the image so production containers do not
# require a bind mount. Build context must be the repo root (see compose files).
USER root
COPY --chown=frappe:frappe master_plan_it/ /home/frappe/frappe-bench/apps/master_plan_it/
RUN pip install -e /home/frappe/frappe-bench/apps/master_plan_it --quiet
USER frappe

ENV PYTHONPATH=/home/frappe/frappe-bench/apps:/home/frappe/frappe-bench/apps/frappe:/home/frappe/frappe-bench/apps/erpnext:/home/frappe/frappe-bench/apps/master_plan_it
